package sys.model;
// Generated 07-ago-2020 22:38:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ChatUsuario generated by hbm2java
 */
public class ChatUsuario  implements java.io.Serializable {


     private Integer id;
     private int chatId;
     private int usuarioId;
     private Date fechaCreacion;

    public ChatUsuario() {
    }

    public ChatUsuario(int chatId, int usuarioId, Date fechaCreacion) {
       this.chatId = chatId;
       this.usuarioId = usuarioId;
       this.fechaCreacion = fechaCreacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getChatId() {
        return this.chatId;
    }
    
    public void setChatId(int chatId) {
        this.chatId = chatId;
    }
    public int getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


