package sys.model;
// Generated 07-ago-2020 22:38:20 by Hibernate Tools 4.3.1



/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private Integer id;
     private int usuarioConctatoId;
     private int usuarioPropietarioId;
     private String telefono;

    public Contacto() {
    }

    public Contacto(int usuarioConctatoId, int usuarioPropietarioId, String telefono) {
       this.usuarioConctatoId = usuarioConctatoId;
       this.usuarioPropietarioId = usuarioPropietarioId;
       this.telefono = telefono;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUsuarioConctatoId() {
        return this.usuarioConctatoId;
    }
    
    public void setUsuarioConctatoId(int usuarioConctatoId) {
        this.usuarioConctatoId = usuarioConctatoId;
    }
    public int getUsuarioPropietarioId() {
        return this.usuarioPropietarioId;
    }
    
    public void setUsuarioPropietarioId(int usuarioPropietarioId) {
        this.usuarioPropietarioId = usuarioPropietarioId;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


