package sys.model;
// Generated 07-ago-2020 22:38:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private Integer id;
     private int chatId;
     private int usuarioId;
     private String mensaje;
     private Date fechaCreacion;

    public Mensaje() {
    }

    public Mensaje(int chatId, int usuarioId, String mensaje, Date fechaCreacion) {
       this.chatId = chatId;
       this.usuarioId = usuarioId;
       this.mensaje = mensaje;
       this.fechaCreacion = fechaCreacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getChatId() {
        return this.chatId;
    }
    
    public void setChatId(int chatId) {
        this.chatId = chatId;
    }
    public int getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


