package sys.model;
// Generated 07-ago-2020 22:38:20 by Hibernate Tools 4.3.1



/**
 * MensajeDocumento generated by hbm2java
 */
public class MensajeDocumento  implements java.io.Serializable {


     private Integer id;
     private int mensajeId;
     private int documentoId;

    public MensajeDocumento() {
    }

    public MensajeDocumento(int mensajeId, int documentoId) {
       this.mensajeId = mensajeId;
       this.documentoId = documentoId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getMensajeId() {
        return this.mensajeId;
    }
    
    public void setMensajeId(int mensajeId) {
        this.mensajeId = mensajeId;
    }
    public int getDocumentoId() {
        return this.documentoId;
    }
    
    public void setDocumentoId(int documentoId) {
        this.documentoId = documentoId;
    }




}


